version: 0.0

os: linux

files:
  - source: target/helloworld.war
    destination: /usr/share/tomcat8/webapps

hooks:

 BeforeInstall:

   - location: scripts/pre.sh

     runas: root

AfterInstall:

   - location: scripts/post.sh

     runas: root


